export enum EventBusType {
  TEST = 'test',
  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS',
  CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS',
  SOCKET_CONNECTED = 'SOCKET_CONNECTED',
  RECEIVE_NEW_ORDER = 'RECEIVE_NEW_ORDER',
  COMPLETED_ORDER = 'COMPLETED_ORDER',
  CUSTOMER_CANCEL = 'CUSTOMER_CANCEL',
  HAVE_PERMISSION_LOCATION = 'HAVE_PERMISSION_LOCATION',
  RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION',
  // ... add more event types as needed
}
