export enum SocketEvents {
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  CONNECTION_ERROR = 'connect_error',
  CONNECTION_TIMEOUT = 'connect_timeout',
  RECONNECT = 'reconnect',
  RECONNECT_ATTEMPT = 'reconnect_attempt',
  RECONNECTING = 'reconnecting',
  RECONNECT_ERROR = 'reconnect_error',
  RECONNECT_FAILED = 'reconnect_failed',
  RECONNECT_ABORTED = 'reconnect_aborted',
  FIND_CLOSET_SHOE_MAKERS = 'find-closest-shoemakers',
  SHOE_MAKER_RESPONSE_TRIP = 'shoemaker-response-trip',
  SHOE_MAKER_REQUEST_TRIP = 'shoemaker-request-trip',
  TRIP_UPDATE = 'trip-update',
  SHOE_MAKER_UPDATE_LOCATION = 'shoemaker-update-location',
  CUSTOMER_CANCEL = 'customer-cancel',
  PAYMENT_STATUS = 'payment-status',
  ONLINE = 'online',
  CLOSE = 'close',
  TIME_OUT = 'timeout',
}
